### ISSUE TITLE
Testing fresh cloning project

### ISSUE THREAD

**Issue by AlejandroCC** [TerVarSoft/TunariApp#1]
Currently It is necessary to test the startup of the project from a fresh clone. @MirkoTV  will be checking this too.  @alejandrocc, @AnghelaLQ please test the installations as soon as possible, you can check wiki page for start app the app [startappPage](https://github.com/TerVarSoft/TunariApp/wiki/Setting-up-to-start-working-with-TunariApp)

**Comment by MirkoTV** [comment]
Hi Tem, Installing the server noticed this:

1. I did not need to run npm  install gulp, I think cause I already installed on my machine and the installation of this tool is not related to the project but to the machine, in that case that should not be an issue @alejandrocc  could you confirm that please?. 

2. Currently I am seeing this message when runnint gulp: ![captura de pantalla 2015-10-11 07 57 12](https://cloud.githubusercontent.com/assets/12484932/10416694/c90863fe-6fed-11e5-892a-9c23019c4c8a.png)
