### ISSUE TITLE
Remove masonry dependecy

### ISSUE THREAD

**Issue by AlejandroCC** [TerVarSoft/TunariApp#11]
It is necessary to remove masonry from the client

**Comment by AlejandroCC** [comment]
Uninstalls the package "masonry" from your bower_components directory 

![1](https://cloud.githubusercontent.com/assets/15057984/10776753/8ea20e54-7cea-11e5-9ab2-388d24945c7f.jpg)

using bower uninstall masonry in client

and we can see that no longer exist the package "masonry" 

![1](https://cloud.githubusercontent.com/assets/15057984/10776830/8d297e1c-7ceb-11e5-9fcd-eec9c785a0ff.jpg)

**Comment by MirkoTV** [comment]
Excellent!, could open a pull request for this??? check this out : #12 , let me know if you need help with this.


Also could you check if after removing masonry the app still works ok?, Mainly check if the "cards"  in products view are created correctly.
