### ISSUE TITLE
Implement Modal Service

### ISSUE THREAD

**Issue by WilmerTV** [TerVarSoft/TunariApp#26]
Currently we will be using this for selling and adding product, however this issue will cover the question modal, other models will be tracked in other issues

**Comment by WilmerTV** [comment]
This looks like a good start : http://dwmkerr.github.io/angular-modal-service/

**Comment by MirkoTV** [comment]
This issue should cover applying this new method for modals to the "delete question" modals in the app, we will open other issues for other modals

**Comment by MirkoTV** [comment]
We are adding a custom build of angular-ui-bootstrap
