### ISSUE TITLE
Remove monk dependecy

### ISSUE THREAD

**Issue by MirkoTV** [TerVarSoft/TunariApp#3]
We are not currently using monk, would be great to removed it

**Comment by AnghelaLQ** [comment]
Remove a package “MONK” from node_modules directory using npm
>npm uninstall monk
To remove it from the dependencies in package .json
>npm uninstall –save monk

note: I don't know how to answer this issue. xD

**Comment by MirkoTV** [comment]
Excellent ! This should work, please open a pull request for this, We should not close an issue util it is completly merged into the organization repository ;)

**Comment by MirkoTV** [comment]
Looks great!, could you try the next test?:     delete your  node modules folder, and re run npm install, since we have succesfully removed monk from package.json file, monk should not be generated anymore, after this, start up the app and verify you can create products and clients succesfuully!.
